require("prototypes.small-street-lamp")
require("prototypes.medium-street-lamp")
require("prototypes.big-street-lamp")
require("prototypes.lighted-substation")
require("prototypes.small-hidden-lamp")
require("prototypes.medium-hidden-lamp")
require("prototypes.big-hidden-lamp")
require("prototypes.substation-hidden-lamp")